version: '3.8'

services:
  web:
    build:
      context: .
    container_name: docbook_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      DATABASE_NAME: docbook
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_HOST: localhost
      DATABASE_PORT: "5432"

  db:
    image: postgres:14
    container_name: docbook_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docbook
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
