# Generated by Django 5.1.4 on 2025-01-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_schedule_day_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Sat'), ('Sunday', 'Sun'), ('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed')], max_length=50),
        ),
    ]
